name: Measure-Object-Layout

on:
  workflow_dispatch:        # bấm nút “Run workflow” thủ công

jobs:
  measure:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '17' ] # thêm '21' nếu muốn

    steps:
    # 1) Lấy mã nguồn của repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2) Cài JDK theo phiên bản trong matrix
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}

    # 3) Tải JOL CLI (full-jar đã kèm jol-core)
    - name: Download JOL CLI
      run: |
        curl -L -o jol-cli.jar \
          https://repo1.maven.org/maven2/org/openjdk/jol/jol-cli/0.17/jol-cli-0.17-full.jar

    # 4) Biên dịch demo dài 100 ký tự
    - name: Compile CompactStringDemo
      run: |
        javac -classpath jol-cli.jar:. CompactStringDemo.java

    # 5) Chạy demo, xuất footprint
    - name: Run demo & capture footprint
      run: |
        JVM_OPTS="-Xms3g -Xmx3g -XX:+UseSerialGC -XX:-UseStringDeduplication \
                  -Djdk.attach.allowAttachSelf=true"
        java $JVM_OPTS -classpath jol-cli.jar:. CompactStringDemo \
          | tee result-${{ matrix.java }}.txt

    # 6) Đưa 40 dòng đầu log vào Job Summary để xem nhanh
    - name: Append summary
      run: |
        echo "## Footprint (100-char strings) – JDK ${{ matrix.java }}" >> $GITHUB_STEP_SUMMARY
        echo '```text' >> $GITHUB_STEP_SUMMARY
        head -n 40 result-${{ matrix.java }}.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
