name: Measure-Object-Layout
on: [workflow_dispatch]

jobs:
  measure:
    runs-on: ubuntu-latest
    strategy:
      matrix: { java: ['8', '17'] }

    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}

    - name: Download JOL CLI
      run: curl -L -o jol-cli.jar \
             https://repo1.maven.org/maven2/org/openjdk/jol/jol-cli/0.17/jol-cli-0.17-full.jar
      
    - name: Compile demo
      run: javac -classpath jol-cli.jar:. CompactStringDemo.java
      
    - name: Run demo & save log
      run: |
          JVM_OPTS="-Xms2g -Xmx2g -XX:+UseSerialGC -XX:-UseStringDeduplication \
                    -Djdk.attach.allowAttachSelf=true"
          java $JVM_OPTS -classpath jol-cli.jar:. CompactStringDemo \
               | tee result-${{ matrix.java }}.txt
